// generated by unplugin-svelte-components
// We suggest you to commit this file into source control
declare global {
    const AboutMe: typeof import("./components/AboutMe.svelte")["default"]
    const ContributionCalendar: typeof import("./components/ContributionCalendar.svelte")["default"]
    const CustomMark: typeof import("./components/blocks/CustomMark.svelte")["default"]
    const ProjectSection: typeof import("./components/ProjectSection.svelte")["default"]
    const ProjectSidebar: typeof import("./components/ProjectSidebar.svelte")["default"]
    const ProjectTechStack: typeof import("./components/ProjectTechStack.svelte")["default"]
    const ProjectTitle: typeof import("./components/ProjectTitle.svelte")["default"]
    const Quote: typeof import("./components/Quote.svelte")["default"]
    const SvelteSeo: typeof import("svelte-seo")["default"]
    const ThemeToggle: typeof import("./components/ThemeToggle.svelte")["default"]
}

export {}
